spring:
  cloud:
    gateway:
      routes:
        # Primary song-service route (port 8082)
        - id: song-service-primary
          uri: http://localhost:8082
          predicates:
            - Path=/song-service/**
          filters: []
          order: -2
        # Fallback song-service route (port 8083)
        - id: song-service-fallback
          uri: http://localhost:8083
          predicates:
            - Path=/song-service/**
          filters: []
          order: -1
        - id: resource-service
          uri: http://localhost:8080
          predicates:
            - Path=/resource-service/**
          filters: []
          order: -1

eureka:
  instance:
    preferIpAddress: true
