spring:
  application:
    name: song-service

  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song-db}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER_SONG:user8082}
    password: ${POSTGRES_PASSWORD_SONG:password8082}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8082
  servlet:
    context-path: /song-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
  sampling:
    probability: 1.0

logging:
  level:
    org.springframework.boot.actuate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-}] %-5level [%thread] %logger{36} - %msg%n"