spring:
  application:
    name: storage-service

  datasource:
    url: ${STORAGE_DB_URL:jdbc:postgresql://localhost:5434/storage-db}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER_STORAGE:user8084}
    password: ${POSTGRES_PASSWORD_STORAGE:password8084}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8084
  servlet:
    context-path: /storage-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
  sampling:
    probability: 1.0

logging:
  level:
    org.springframework.boot.actuate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-}] %-5level [%thread] %logger{36} - %msg%n"
