# Build stage
FROM maven:3.9.9-eclipse-temurin-17-alpine AS build
WORKDIR /app

# Copy the parent POM and full source code for correct Maven context
COPY . /app

# Install dependencies without running tests
RUN mvn install -DskipTests

# Cache Maven dependencies specific to the submodule
WORKDIR /app/authorization-server
RUN mvn dependency:go-offline

# Build the submodule
COPY ./authorization-server/src /app/authorization-server/src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre-alpine-3.21
WORKDIR /app

# Install curl
RUN apk add --no-cache curl

# Copy the built jar file
COPY --from=build /app/authorization-server/target/*.jar app.jar

EXPOSE 9000
CMD ["java", "-jar", "app.jar"]
